void CheckFinishNormalNew(int seed, apvector <int> inExceptions);
void CheckFinishVeteranNew(int seed, apvector <int> inExceptions);
void CheckFinishEasyNew(int seed, apvector <int> inExceptions);
void CheckFinishHypermodeNew(int seed, apvector <int> inExceptions);
void resetFlags();
void printList();
bool returnCompletableVeteran();
bool returnCompletableNormal();
bool returnCompletableEasy();
bool returnCompletableHypermode();
string returnSeed();
string returnExceptions();
apvector <string> getItemNames();
apvector <string> getAreaNames();
apvector <int> shrinkIntVector(apvector <int> inVector);
apvector <int> removeIntElement(apvector <int> inVector, int element);
apvector <string> shrinkStringVector(apvector <string> inVector);
apvector <string> removeStringElement(apvector <string> inVector, int element);
apvector <string> randomize(apvector <string> originalList, apvector <int> excludedItems, int seed);
